name: GregCraft
main: com.gmail.gregrockss.gregcraft.Main
version: 0.0.98
uthor: Threebuddies
description: CounterCraft Clone
commands:  
  kit:
    description: Give you 20 bricks and 3 diamonds
    usage: /kit
  basicbow:
    description: Gives an infinity bow
    usage: /basicbow
  assign:
    description: Assign players to teams.
  myteam:
    description: Gets your team!